NewsScraper/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^', include('main.urls')),
    url(r'^account/', include('account.urls')),
]

main/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

from main import views as main_views

app_name = 'main'

urlpatterns = [

    url(r'^$', main_views.HomePageView.as_view(), name="home"),

    url(r'^search', main_views.SearchForm.as_view(), name="search_news"),
    url(r'^(?P<slug>[\w-]+)/$', main_views.news_list, name="news_list"),
    url(r'^(?P<username>[\w-]+)/watch-later-list/', main_views.watch_later_list, name="watch_later_list"),
    url(r'^(?P<username>[\w-]+)/history/', main_views.history_list, name="history"),

    url(r'^(?P<website_slug>[\w-]+)/(?P<slug>[\w-]+)/$', main_views.NewsDetailsView.as_view(), name="news_detail"),
    url(r'hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),

    url(r'^watch-later/(?P<id>\d+)', main_views.watch_later_add_remove, name="watch_later_add_remove"),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    

main/models.py
# built it
from django.db.models.signals import pre_delete, pre_save
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.dispatch import receiver
from django.db import models

# outside
from hitcount.models import HitCountMixin, HitCount
from scrapy_djangoitem import DjangoItem
from dynamic_scraper.models import Scraper, SchedulerRuntime
from datetime import datetime

# my own project
from NewsScraper.utils import unique_slug_generator_name, unique_slug_generator_title


class WebsiteInfo(models.Model):
    key = models.CharField(max_length=30)
    search_domain = models.CharField(max_length=200)
    scraper = models.ForeignKey(
        Scraper, blank=True, null=True, on_delete=models.SET_NULL)
    image = models.ImageField(
        max_length=256, upload_to='website_pics', blank=True, null=True)

    def __str__(self):
        return self.key


class NewsWebsite(models.Model):
    name = models.CharField(max_length=200)
    url = models.URLField()
    scraper = models.ForeignKey(
        Scraper, blank=True, null=True, on_delete=models.SET_NULL)
    scraper_runtime = models.ForeignKey(
        SchedulerRuntime, blank=True, null=True, on_delete=models.SET_NULL)
    slug = models.SlugField(unique=True, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_website_name(self):
        return self.name[:3]


class News(models.Model):
    title = models.CharField(max_length=200)
    news_website = models.ForeignKey(NewsWebsite)
    description = models.TextField(blank=True)
    image = models.URLField()
    url = models.URLField()
    watch_later = models.ManyToManyField(
        User, related_name='watch_later', blank=True)
    checker_runtime = models.ForeignKey(
        SchedulerRuntime, blank=True, null=True, on_delete=models.SET_NULL)
    slug = models.SlugField(unique=True, null=True, blank=True)
    hit_count_generic = GenericRelation(
        HitCount, object_id_field='object_pk', related_query_name='hit_count_generic_relation')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    # def get_date(self):
    #     time = datetime.now()
    #     if self.create_at.day == time.day:
    #         return str(time.hour - self.create_at.hour) + " hours ago"
    #     else:
    #         if self.create_at.month == time.month:
    #             return str(time.day - self.create_at.day) + " days ago"
    #         else:
    #             if self.create_at.year == time.year:
    #                 return str(time.month - self.create_at.month) + " months ago"
    #     return self.create_at


class NewsItem(DjangoItem):
    django_model = News


@receiver(pre_delete)
def pre_delete_handler(sender, instance, using, **kwargs):
    if isinstance(instance, News):
        if instance.checker_runtime:
            instance.checker_runtime.delete()


pre_delete.connect(pre_delete_handler)


# function to create a slug using the function (unique_slug_generator_name) that exist in the module (utils.py)
def create_slug_name(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator_name(instance)


# function to create a slug using the function (unique_slug_generator_title) that exist in the module (utils.py)
def create_slug_title(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator_title(instance)


pre_save.connect(create_slug_name, sender=NewsWebsite)
pre_save.connect(create_slug_title, sender=News)

main/views.py
# built it
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import TemplateView, ListView, DetailView
from django.db.models import Q

# outside
from hitcount.views import HitCountDetailView
from hitcount import models as hitcount_models

# my own project
from main import models as main_models
from main.tasks import single_crawl_without_scheduling
from main.weather import get_weather


class HomePageView(TemplateView):
    template_name = "main/home.html"

    def get_context_data(self, *args, **kwargs):
        context = super(HomePageView, self).get_context_data(*args, **kwargs)
        context['most_popular'] = main_models.News.objects.order_by('-hit_count_generic__hits')[:3]
        context['most_popular_ny_times'] = main_models.News.objects.filter(
            news_website__name__startswith='New York Times').order_by('-hit_count_generic__hits')[:5]
        context['most_popular_roya'] = main_models.News.objects.filter(
            news_website__name__startswith='Roya').order_by('-hit_count_generic__hits')[:5]
        context['most_popular_jordan_times'] = main_models.News.objects.filter(
            news_website__name__startswith='Jordan Times').order_by('-hit_count_generic__hits')[:5]
        context['most_popular_aljazeera'] = main_models.News.objects.filter(
            news_website__name__startswith='Aljazeera').order_by('-hit_count_generic__hits')[:5]
        context['most_popular_technology'] = main_models.News.objects.filter(
            news_website__name__startswith='Technology').order_by('-hit_count_generic__hits')[:5]
        context['most_popular_business'] = main_models.News.objects.filter(
            news_website__name__startswith='Business').order_by('-hit_count_generic__hits')[:5]
        return context


def news_list(request, slug):

    news_list = main_models.News.objects.filter(
        news_website__slug=slug).order_by('-create_at', 'title')
    context = {
        'news_list': pagination(request, news_list),
    }
    context.update(strip_website_name_and_breadcrumb(slug))
    return render(request, 'main/news_list.html', context)


class NewsDetailsView(HitCountDetailView):
    model = main_models.News
    template_name = 'main/news_detail.html'
    context_object_name = 'news_detail'
    slug_field = 'slug'
    # set to True to count the hit
    count_hit = True

    def get_context_data(self, **kwargs):
        context = super(NewsDetailsView, self).get_context_data(**kwargs)
        news_title = main_models.News.objects.get(slug=self.kwargs['slug'])

        context['website_slug'] = self.kwargs['website_slug']
        context['most_popular_news'] = main_models.News.objects.filter(
            Q(news_website__slug=self.kwargs['website_slug']) &
            ~Q(title=news_title.title)
        ).order_by('-hit_count_generic__hits')[:8]

        context.update(strip_website_name_and_breadcrumb(
            self.kwargs['website_slug']))
        return context


class SearchForm(TemplateView):

    def get(self, request, *args, **kwargs):
        text = str(request.GET['search_text']).strip(' !@#$%^&*()_+-')
        websites_list = request.GET.getlist('check')
        context = {'search_result': 'exits', }

        if text:
            context['text'] = text
            text_split = text.split(' ')
            text_split = ('_'.join(text_split)).strip('_')
            data_news = []
            news_count = 0
            if websites_list:
                for website in websites_list:
                    result = main_models.News.objects.filter(
                        (Q(title__icontains=text) &
                         Q(news_website__name__startswith=website))
                        |
                        (Q(news_website__name__icontains=text_split) &
                         Q(news_website__name__startswith=website))
                    ).order_by('-create_at')
                    data_news += result
                    news_count += result.count()

                if data_news == []:
                    there_have_news = single_crawl_without_scheduling(
                        text, websites_list)
                    for website in websites_list:
                        result = main_models.News.objects.filter(
                            (Q(title__icontains=text) &
                             Q(news_website__name__startswith=website))
                            |
                            (Q(news_website__name__icontains=text_split) &
                             Q(news_website__name__startswith=website))
                        ).order_by('-create_at')
                        data_news += result
                        news_count += result.count()

                context['news_count'] = news_count
                context['news_list'] = pagination(request, data_news)
                context['websites_list'] = websites_list
                context['websites_list_search'] = websites_list
                return render(request, 'main/news_list.html', context)

            else:
                data_news = main_models.News.objects.filter(
                    Q(title__icontains=text) |
                    Q(news_website__name__icontains=text_split)
                ).order_by('-create_at')
                context['news_count'] = data_news.count
                context['news_list'] = pagination(request, data_news)
                return render(request, 'main/news_list.html', context)

        else:
            messages.error(request, "Invalid Text, please try again!")
            return redirect(reverse('main:home'))


@ login_required(login_url='/account/register-login')
def watch_later_add_remove(request, id):
    url = request.META.get('HTTP_REFERER')
    news = get_object_or_404(main_models.News, id=id)
    if news.watch_later.filter(id=request.user.id).exists():
        news.watch_later.remove(request.user)
        # messages.warning(request, f'{book.name} removed from favourites.')
    else:
        news.watch_later.add(request.user)
        # messages.success(request, f'{book.name} added to favourites.')
    if 'account' in url:
        return HttpResponseRedirect("/")
    return HttpResponseRedirect(url)


@ login_required(login_url='/account/register-login')
def watch_later_list(request, username):

    watch_later_news = main_models.News.objects.filter(
        watch_later=request.user.id)

    news_count = watch_later_news.count
    context = {
        'watch_later': 'exist',
        'news_count': news_count,
        'news_list': pagination(request, watch_later_news)
    }
    return render(request, 'main/news_list.html', context)


@ login_required(login_url='/account/register-login')
def history_list(request, username):

    history_list = hitcount_models.Hit.objects.filter(user_id=request.user.id)
    data_news = []
    news_count = 0
    if history_list:
        for news in history_list:
            result = main_models.News.objects.filter(
                title__icontains=news.hitcount)
            data_news += result
            news_count += result.count()

    context = {
        'history': 'exist',
        'news_count': news_count,
        'history_list': history_list,
        'news_list': pagination(request, data_news)
    }

    return render(request, 'main/news_list.html', context)


def strip_website_name_and_breadcrumb(slug):

    context = {}
    website_breadcrumb = ''
    websites_names = ''

    names = ['Technology', 'Business', 'New York Times ',
             'Roya ', 'Jordan Times', 'Aljazeera ']

    website_breadcrumb = main_models.NewsWebsite.objects.filter(
        slug=slug)[0]
    websites_names = str(website_breadcrumb.name)
    for name in names:
        if name in websites_names:
            context['website_categories'] = main_models.NewsWebsite.objects.filter(
                name__startswith=name)
            break
    context['website_breadcrumb'] = website_breadcrumb
    return context


# function to check if the slug is exist and return none if not.
def check_on_slug(slug):

    if slug.exists():
        slug = slug.first()
        return slug
    else:
        return None


def pagination(request, news_list):

    paginator = Paginator(news_list, 9)
    page = request.GET.get('page', 1)
    try:
        news_list = paginator.page(page)
    except PageNotAnInteger:
        news_list = paginator.page(1)
    except EmptyPage:
        news_list = paginator.page(paginator.num_pages)

    return news_list

templates/main/news_detail.html
{% extends "base/layout/layout.html" %}
{% load static %}
{% load i18n %}
{% load hitcount_tags %}

{% block site_title %}
{{ news_detail.title }}
{% endblock %}

{% block content %}

<!-- Content -->
<section class="bg0 p-t-10">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10 col-lg-8 p-b-30">
                <div class="p-r-10 p-r-0-sr991">
                    <!-- Blog Detail -->
                    <div class="p-b-70">
                        {% if '_' not in news_detail.news_website.name %}
                        <a href="{% url 'main:news_list' slug=news_detail.news_website.slug %}"
                            class="f1-s-10 cl2 hov-cl10 trans-03 text-uppercase">

                            {{ news_detail.news_website.name }}

                        </a>
                        {% endif %}
                        <h3 class="f1-l-3 cl2 p-b-16 p-t-33 respon2">
                            {{ news_detail.title }}

                        </h3>

                        <div class="flex-wr-s-s p-b-40">
                            <span class="f1-s-3 cl8 m-r-15">
                                <span>
                                    {{ news_detail.update_at }}
                                </span>
                            </span>

                            <span class="f1-s-3 cl8 m-r-15">
                                {% get_hit_count for news_detail %} <i class="fa fa-eye" title="views"
                                    aria-hidden="true"></i>
                            </span>
                        </div>

                        <div class="wrap-pic-max-w p-b-30">
                            <img src="{{ news_detail.image }}" alt="IMG">
                        </div>

                        <p class="f1-s-11 cl6 p-b-25">
                            {{ news_detail.description|capfirst }}.
                        </p>

                        <a href="{{ news_detail.url }}">Check the article in the Original Website</a>
                    </div>
                </div>
            </div>

            <!-- Sidebar -->
            <div class="col-md-10 col-lg-4 p-b-30">
                <div class="p-l-10 p-rl-0-sr991 p-t-70">

                    <!-- Popular Posts -->
                    <div class="p-b-30">
                        <div class="how2 how2-cl4 flex-s-c">
                            <h3 class="f1-m-2 cl3 tab01-title">
                                Popular News
                            </h3>
                        </div>
                        {% if most_popular_news %}
                        <ul class="p-t-35">

                            {% for news in most_popular_news %}
                            <li class="flex-wr-sb-s p-b-30">
                                <a href="{% url 'main:news_detail' website_slug=news.news_website.slug slug=news.slug %}"
                                    class="size-w-10 wrap-pic-w hov1 trans-03">
                                    <img src="{{ news.image }}" alt="IMG">
                                </a>

                                <div class="size-w-11">
                                    <h6 class="p-b-4">
                                        <a href="{% url 'main:news_detail' website_slug=news.news_website.slug slug=news.slug %}"
                                            class="f1-s-5 cl3 hov-cl10 trans-03">
                                            {{ news.title }}
                                        </a>
                                    </h6>

                                    <span class="cl8 txt-center p-b-24">
                                        <span class="f1-s-3 m-rl-3">
                                            {% get_hit_count for news %} <i class="fa fa-eye" title="Total views"
                                                aria-hidden="true"></i>
                                        </span>

                                        <span class="f1-s-3 m-rl-3">
                                            -
                                        </span>

                                        <span class="f1-s-3">
                                            {{ news.create_at|date:"M d" }}
                                        </span>
                                    </span>
                                </div>
                            </li>
                            {% endfor %}

                        </ul>
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/main/news_list.html
{% extends "base/layout/layout.html" %}
{% load static %}
{% load i18n %}
{% load hitcount_tags %}


{% block site_title %}
{% if search_result %}

{% if text %}
{{ text }} - MagNews Search
{% endif %}

{% elif history %}
History

{% elif watch_later %}
Watch Later

{% else %}

{{ website_breadcrumb.name|title }}

{% endif %}
{% endblock %}

{% block content %}

{% include 'main/extra/breadcrmb.html' %}

<!-- Page heading -->
<div class="container p-t-4 p-b-15">
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <h2 class="f1-l-1 cl2 p-b-15">
                {% if search_result %}

                <div class="search-result-text">
                    {% if text %}

                    {{ news_count }} Results Found for "<span>{{ text }}</span>"
                    {% if websites_list %}
                    in
                    {% for website in websites_list %}
                    <span>{{ website }}</span>
                    {% if forloop.counter < websites_list|length %} ,{% endif %}
                    {% endfor %}
                    {% endif %}

                    {% else %}

                    {{ news_count }} Results Found in
                    {% for website in websites_list %}
                    <span>{{ website }}</span>
                    {% if forloop.counter < websites_list|length %} ,{% endif %}
                    {% endfor %}

                    {% endif %}
                </div>

                {% elif watch_later %}
                (<span>{{ news_count }}</span>) Found - Watch Later

                {% elif history %}
                (<span>{{ news_count }}</span>) Found - History

                {% else %}

                {% if website_breadcrumb.name == 'Business Arabian Business'  %}
                Arabian Business
                {% elif "Technology" in website_breadcrumb.name or "Business" in website_breadcrumb.name %}
                {{ website_breadcrumb.name|cut:'Technology'|cut:'Business' }}
                {% else %}
                {{ website_breadcrumb.name|cut:'New York Times'|cut:'Roya'|cut:'Jordan Times'|cut:'Aljazeera' }}
                {% endif %}- Latest News

                {% endif %}

            </h2>
        </div>
        {% if news_list %}
        <div class="col-md-6 col-sm-12">
            <div class="upper-pagination">
                <!-- Pagination -->
                {% include 'main/extra/paginator.html' %}
            </div>
        </div>
        {% endif %}
    </div>

</div>


<!-- Post -->
<section class="bg0 p-t-10 p-b-55">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-12 p-b-80">
                <div class="row">

                    {% if news_list %}
                    {% for news in news_list.object_list %}
                    <div class="col-md-4 col-sm-6 col-xs-12 p-r-25 p-r-15-sr991">
                        <!-- Item latest -->
                        <div class="m-b-45">
                            <a href="{% url 'main:news_detail' website_slug=news.news_website.slug slug=news.slug %}"
                                class="wrap-pic-w hov1 trans-03 img-size">
                                <div class="container-img">
                                    <img src="{{ news.image }}" alt="Avatar" class="image">
                                    <div class="middle">
                                        <div class="text-img">
                                            {% if user in news.watch_later.all %}
                                            <a href="{% url 'main:watch_later_add_remove' id=news.id %}"
                                                title="Remove from Watch Later"><i class='fas fa-clock'></i></a>
                                            {% else %}
                                            <a href="{% url 'main:watch_later_add_remove' id=news.id %}"
                                                title="Add to Watch Later"><i class='far fa-clock'></i></a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </a>

                            <div class="p-t-16">
                                <h5 class="p-b-5">
                                    <a href="{% url 'main:news_detail' website_slug=news.news_website.slug slug=news.slug %}"
                                        class="f1-m-3 cl2 hov-cl10 trans-03">
                                        {{ news.title }}
                                    </a>
                                </h5>

                                <span class="cl8">
                                    {% if search_result or history %}
                                    {% if "_" not in news.news_website.name %}
                                    <a href="{% url 'main:news_list' slug=news.news_website.slug %}"
                                        class="f1-s-4 cl8 hov-cl10 trans-03">
                                        {{ news.news_website.name }}
                                    </a>
                                    <span class="f1-s-3 m-rl-3">
                                        -
                                    </span>
                                    {% endif %}
                                    {% endif %}
                                    <span class="f1-s-3">
                                        {{ news.create_at|date:"M d" }}
                                    </span>
                                    <span class="f1-s-3 m-rl-3">
                                        -
                                    </span>
                                    <span class="f1-s-3 m-rl-3">
                                        {% get_hit_count for news %} <i class="fa fa-eye" title="Total views"
                                            aria-hidden="true"></i>
                                    </span>
                                </span>
                                <br>
                                {% if history %}
                                <span class="cl8">
                                    Watched Date:
                                    <span class="f1-s-3">

                                        {% for show in history_list %}
                                        {% if news.title|lower == show.hitcount|lower %}
                                        {{ show.created }}
                                        {% endif %}
                                        {% endfor %}

                                    </span>
                                </span>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% endif %}

                    <hr>

                </div>
                {% if news_list %}
                <!-- Pagination -->
                {% include 'main/extra/paginator.html' %}
                {% endif %}
            </div>

        </div>
    </div>
</section>

{% for news in watch_later_news_test %}
{{ news }}
<br><br>
{% endfor %}


{% endblock %}